### ISSUE TITLE
Refactoring suggestions

### ISSUE THREAD

**Issue by shyuep** [materialsvirtuallab/megnet#1]
Here are some changes I suggest for the organization:

1. Instead of having the highly specific QM9 and MP packages, I suggest you build an interface which assembles the input based on a list of pymatgen Structures/Molecules and the target properties they wish to learn. This will allow people to use the MEGNet from conceivably any set of structures they wish to use.
2. You can retain the data.mp and data.qm9 as specific examples of how to leverage on the classes in part 1 to build a model.

**Comment by chc273** [comment]
@shyuep accepted. Will work on it.
