### ISSUE TITLE
Error in transfer_learning notebook

### ISSUE THREAD

**Issue by arosen93** [materialsvirtuallab/megnet#109]
In `notebooks/transfer_learning.ipynb`, there is a line reading
```python
embedding_layer_index = [i for i, j in enumerate(model.layers) if j.name.startswith('embedding')][0]
```
This throws an error of `IndexError: list index out of range`. I believe the line should be rewritten to be
```python
embedding_layer_index = [i for i, j in enumerate(model.layers) if j.name.startswith('atom_embedding')][0]
```

**Comment by chc273** [comment]
Thanks! @arosen93 
At one point, we decided to name the layers explicitly, hence causing the naming inconsistency. 

The example has been revised.
