### ISSUE TITLE
load_model segmentation fault

### ISSUE THREAD

**Issue by 775019309** [materialsvirtuallab/megnet#122]
The installation packages all meet the version requirements, but an error will be reported when "load_model" is loaded. The fault type seems to force me to use GPU, segmentation fault.

**Comment by chc273** [comment]
The codes are not dependent on GPU and there is no default type for tensorflow. It is just the one you installed. Make sure you tensorflow is properly installed.

**Comment by 775019309** [comment]
Yes, thank you so much. I also have a question that I have some CIF files now, how can I use pymatgen to make them into a data set, so that I can read many structures at once, how can I convert them into a json files ?  I would appreciate it if you could give me some codes.

**Comment by chc273** [comment]
pymatgen Structure has Structure.from_file method to load the cif files to Structure objects. You can work with the objects to train a model. Please check the examples in notebooks. If you really want the json files you can use megnet.data.crystal.CrystalGraph and then use the convert method to convert Structure to a dictionary for saving in json.
