### ISSUE TITLE
What to do with negative values of Bulk Modulus and Shear Modulus?

### ISSUE THREAD

**Issue by ysharshit** [materialsvirtuallab/megnet#124]
Hi
When we set up the model for properties like bulk modulus and shear modulus, we take into account the log10(GPa) values. For some crystals, the values of bulk and shear moduli come out to be negative. The question is how do we take the logarithm? Do we take the absolute values before calculating the logarithm? Or do we take only those crystals which have positive values for these properties?
I will be grateful to you if you can answer.
Thanks

**Comment by chc273** [comment]
We keep only those with positive values

**Comment by ysharshit** [comment]
Hi Chen 
Thanks a lot

**Comment by chc273** [comment]
No problem
