### ISSUE TITLE
Hardcoded reading of json as opposed to hdf5

### ISSUE THREAD

**Issue by arosen93** [materialsvirtuallab/megnet#125]
In the README, it says you can do `model = MEGNetModel.from_file('mvl_models/qm9-2018.6.1/HOMO.hdf5')`. However, if I'm understanding it correctly, the `from_file` function [here](https://github.com/materialsvirtuallab/megnet/blob/master/megnet/models/base.py) is hard-coded to read in a `.json` (line 339). Am I understanding this correctly?

**Comment by chc273** [comment]
Hi, the model weights are in hdf5 (keras model save) and the associated graph descriptor etc are in associated json. The model will read these two files during loading. Correspondingly in the saving process, model.hdf5 and the associated model.hdf5.json are saved.

**Comment by arosen93** [comment]
Ah, I misunderstood. Thanks for the clarification. It's looking for the hdf5.json. I see that now.
