### ISSUE TITLE
Suggestion for improvement in default parameter

### ISSUE THREAD

**Issue by googhgoo** [materialsvirtuallab/megnet#157]
Hello, 

I'm raising this issue in hope to improve the default behavior of the megnet. I have ran into a very reproducible training failure for binary classification task (e.g. MEGNetModel(..., is_classification=True)). The default behavior of the model training often leads to predicting Nan values due to the exploding gradient. To make the training more robust, clipnorm (typically between 1 and 5) parameter can be set for optimizer (Adam) which clips gradient. This can be added to opt_params in __init__ of MEGNetModel class in the case of binary classification task to make the default behavior more robust. I'm not sure if improving the default behavior is of your interest, but I hope this helps!

Another issue I noted was that the callback class, ReduceLRUponNan, leaded to error for me which raised "FailedPreconditionError: Attempting to use uninitialized value." I did not have a chance to address this issue as clipnorm solved my problem, but it seems like the model parameters are not initialized after loading weights.

best regards,
Geun Ho Gu

**Comment by chc273** [comment]
Hi Geun Ho @googhgoo 

Thanks for raising the issues. For the exploding gradients, yes, we do have an option in the `init` called `optimizer_kwargs` which can be used to set `clipnorm` and `clipvalue`. Currently, the default of `optimizer_kwargs` is None. I will think about it whether to have default `clipnorm` and `clipvalue`.

For the second issue, it seems to be also related to tensorflow versions. I will further investigate it when such problem arises. So far, I have not seen such issues.

**Comment by chc273** [comment]
@googhgoo I have tested a few cases, in deed the gradient clipped default behavior can be helpful to some fittings. I am changing the default arguments for `clipnorm` for the optimizer. Thanks for the suggestion!
