### ISSUE TITLE
predict_structure only producing first target when ntargets=2

### ISSUE THREAD

**Issue by Ash-Pera** [materialsvirtuallab/megnet#163]
Hello,
I was wondering how to get the other predictions when ntargets is greater than 0. When I do `model.predict_structure(structure)`, I seem to get an array containing only the first prediction. Do I need to set a different `target_scaler` to be able to do this? If so, what should it be?

**Comment by chc273** [comment]
@Ash-Pera  

The following dummy model gives me a vector of 2 for the prediction, as expected. 

```
from megnet.models import MEGNetModel
from pymatgen import Structure, Lattice
s = Structure(Lattice.cubic(3.16), ['Mo', 'Mo'], [[0., 0., 0.], [0.5, 0.5, 0.5]])

model = MEGNetModel(100, 2, ntarget=2)
model.predict_structure(s)
```

**Comment by Ash-Pera** [comment]
Thank you for the reply, I will check my model again

**Comment by Ash-Pera** [comment]
Seems to be an issue with how I build my model - sorry to bother you.
