### ISSUE TITLE
On the error for the prediction 

### ISSUE THREAD

**Issue by okunoyukihiro** [materialsvirtuallab/megnet#2]
Dear megnet developers. 

I'm interested on the crystal graph network and examined  the machine learning for elastic moduli with the help of the sample code on megnet github page. 
 
I used the data from elastic moduli 
https://figshare.com/articles/Graphs_of_materials_project/7451351

However,  I found the error message from the prediction of new structure which has only 1 atom in the crystal cell. 

InvalidArgumentError    Traceback (most recent call last)
InvalidArgumentError: segment_ids should be the same size as dimension 0 of input.

The error seems tensorflow error for the input structure for prediction crystal structure but 
I set simply pymatgen structure ojbect made from cif file. 

I found the error was always occurred at the prediction of 1 atom crystal cell like "Si"  from the training crystal graph model .

model.predict_structure(st)
where st is pymatgen structure object with crystal which has  only 1 atom in the unit cell. 

If I get reply and suggestion for the error, I’m very grateful. 

My python code is as follow

import json
import gzip 
import numpy as np
from megnet.data.mp import index_rep_from_structure, to_list,graph_to_inputs
import os 
from pymatgen.core import Structure 
import pandas as pd 
from matplotlib import pyplot as plt

data_json_file = "../megnet/data/tests/mp_elas.json"
with open (data_json_file,'r') as f:
    data = pd.read_json(f)

target_cols = ['K']

is_null = data[target_cols].apply(pd.isnull, axis=1)
rows_to_drop = data[is_null.values].index

print('target null number =',len(rows_to_drop))

data = data.drop(rows_to_drop, axis=0)
data = data.dropna(axis=0)

from pymatgen.io.cif import CifParser

for target_col in target_cols:
    plt.title(target_col)
    plt.hist(data[target_col], bins=50)
    plt.show()
    

structures = []
for i in range(len(data.index)):
    cif =  CifParser.from_string(data.iloc[i]['structure'])
    st = cif.get_structures()[0]
    structures.append(st)
    if(len(st.sites)==1):
        print('sites is 1')
        graph = data.iloc[i]['graph']
        print (graph)
        name = st.formula
        print (name)
        
structures = pd.Series(structures)

from megnet.model import megnet_model
from megnet.data.graph import GaussianDistance
from megnet.data.crystal import CrystalGraph,structure2graph
from sklearn.model_selection import KFold
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

import matplotlib.pyplot as plt
get_ipython().run_line_magic('matplotlib', 'inline')

n_bond_feature = 10
n_global_feature = 2
gaussian_centers = np.linspace(0, 5, 10)
gaussian_width = 0.5

graph_convertor = CrystalGraph()
distance_convertor = GaussianDistance(gaussian_centers, gaussian_width)

targets =data[target_cols[0]]

kf = KFold(n_splits=5, shuffle=True)

X = structures
Y = targets

        
for train_index, test_index in kf.split(X,Y):
    print('train index =',train_index,'test_index=',test_index)
    X_tra, X_test = X.iloc[train_index].tolist(), X.iloc[test_index].tolist()
    y_tra, y_test = Y.iloc[train_index].tolist(), Y.iloc[test_index].tolist()
    
 
    
    model = megnet_model(n_bond_feature,n_global_feature, 
 graph_convertor=graph_convertor, distance_convertor = distance_convertor)    
    hist = model.train(X_tra,y_tra,epochs=20)

    model.summary()
            
    plt.rcParams['font.size'] = 20
    plt.figure(figsize=(8, 6))
    plt.plot(model.history.history['loss'], 'o-r', label='Train Loss')
    plt.xlabel('Epoch')
    plt.ylabel("Loss (a.u.)")
    plt.legend(frameon=False)

    pred_test = []
    for i,st in enumerate(X_test):

        st_pre = model.predict_structure(st)
        pred_test.append(st_pre[0])
        print('ypred =',st_pre[0],'ans=',y_test[i])
    

    mse = mean_squared_error(y_test, pred_test)
    print("KERAS REG TEST RMSE : %.2f" % (mse ** 0.5))

**Comment by chc273** [comment]
@okunoyukihiro A fix has been pushed. Thank you.

**Comment by shyuep** [comment]
Thanks for reporting this. This is due to the special case of single atom array that we need to handle in tensorflow. It is now fixed.

**Comment by okunoyukihiro** [comment]
Dear megnet developer : Dr Ong and Chen.

Thank you for fixing source code.  I always  read your studies. 
If I found some trouble in using megnet,  I will report problem. 

Sincerely.

Yukihiro Okuno
