### ISSUE TITLE
Type Error while Training a new MEGNetModel from structures

### ISSUE THREAD

**Issue by kdmsit** [materialsvirtuallab/megnet#200]
I was trying run a new model as suggested by you:

from megnet.models import MEGNetModel
from megnet.data.crystal import CrystalGraph
import numpy as np
from pymatgen.core.structure import Structure

nfeat_bond = 100
r_cutoff = 5
gaussian_centers = np.linspace(0, r_cutoff + 1, nfeat_bond)
gaussian_width = 0.5
graph_converter = CrystalGraph(cutoff=r_cutoff)
model = MEGNetModel(graph_converter=graph_converter, centers=gaussian_centers, width=gaussian_width)

But got the following error:
**TypeError: Failed to convert object of type <class 'tuple'> to Tensor. Contents: (Dimension(96), 64). Consider casting elements to a supported type.**

Please help

**Comment by chc273** [comment]
@kdmsit can you give a minimal example to reproduce your error? From the error, It can be related to the data you use too

**Comment by kdmsit** [comment]
Data is being used from **megnet.data.crystal import CrystalGraph** it seems !!

**Comment by chc273** [comment]
CrystalGraph is just a way to convert your crystal structures (pymatgen Structure objects) into a graph. Please see my previous comment

**Comment by kdmsit** [comment]
I didnot get you. I have not read any data yet. 
Crsytal Graph structures (pymatgen Structure objects)  I am getting from **"from megnet.data.crystal import CrystalGraph"**. Later that is converted to graph using **graph_converter = CrystalGraph(cutoff=r_cutoff)**.
Then when I am initialising the model by **model = MEGNetModel(graph_converter=graph_converter, centers=gaussian_centers, width=gaussian_width)**, I am getting the error. I am getting this error to initialise the model.

**Comment by chc273** [comment]
@kdmsit I copied and pasted the code, but it runs fine on my laptop. Please try to update megnet to latest github version and also update tensorflow.

**Comment by kdmsit** [comment]
Thanks a lot!!.. it worked. TensorFlow version issue was there.

One more thing I just want to ask. To train it for large data like around 30K what should be the suitable epochs and nfeat_bond ?

**Comment by chc273** [comment]
It really depends on the type of the data, maybe you can try the nfeat_bond 100 and epoch 1000.

**Comment by kdmsit** [comment]
I have run the model for Band-Gap with 20%(7300 Materials) I used to train and rest 80% test (30K). I got around MAE as 1.43. Can you comments on this?
I think this is far more than other baselines?

**Comment by chc273** [comment]
@kdmsit yes that’s too high in general, but is possible depending on the data you used. For MP data, this is way too high
