### ISSUE TITLE
Superconducting Critical temperature model

### ISSUE THREAD

**Issue by marcoloco23** [materialsvirtuallab/megnet#212]
Great work so far! I have been thinking about creating a model predicting the superconducting critical temperature based on the crystal structure. So far, however, I am having trouble finding appropriate training data... Supercon's dataset is the best I have found (https://supercon.nims.go.jp/supercon/material_menu). Have you considered developing such a model yourself, and if so, what have been the main issues you faced? Thanks for all the work you have done.

**Comment by chc273** [comment]
@marcoloco23 we are not working on superconductors. At some time point I also looked into this field and had the same issue as yours. The SuperCon database seems only have formula, and no structures. Such type of data is not very suitable for structure based models like megnet. If you are able to map the formula to structure, then you may give it a try
