### ISSUE TITLE
Atomic embeddings for QM9 models

### ISSUE THREAD

**Issue by araquejc** [materialsvirtuallab/megnet#226]
When reading atomic embeddings from QM9 models (MEGNet-simple) from files, for example:

```
model_h = MEGNetModel.from_file('../mvl_models/qm9-2018.6.1/H.hdf5')
embedding_layer = [i for i in model_h.layers if i.name.startswith('embedding')][0]
embedding = embedding_layer.get_weights()[0]
print('Embedding matrix dimension is ', embedding.shape)
```
One obtains the following:
`Embedding matrix dimension is  (9, 16)`

How is this matrix embedding atoms H,C,N,O,F if the atomic number goes up to 9 (F)?

**Comment by chc273** [comment]
@araquejc for historic reasons, the QM9 models were built by using atom types, so the model will first convert the atomic number to the corresponding type before passing it to the model. 

https://github.com/materialsvirtuallab/megnet/blob/0047e04f3762433590d0bdda37bbb6ef6cf4cab2/megnet/data/qm9.py#L10

**Comment by chc273** [comment]
@araquejc To be precise, our original qm9 models were initially trained on the processed qm9 dataset by Faber et. al. J. Chem. Theory Comput. 2017, 13, 11, 5255–5264, where they have atom types (integer) instead of atomic number. In later model developments, we decided to use the atomic number for graph construction, so we had to make this conversion to be compatible.

**Comment by araquejc** [comment]
@chc273 Thanks for your quick reply!

Does that means that in the code above `embedding[1]` == "H", `embedding[2]` == "C", `embedding[4]` == "N", `embedding[6]` == "O" and `embedding[8]` == "F"?

**Comment by chc273** [comment]
Yes you are right @araquejc

**Comment by araquejc** [comment]
Thanks again! That was my initial guess, but I wanted to cross check with you. I think it is useful to know this before trying transfer learning for MEGNet models reading pymatgen molecules directly (i.e., using atomic number).

**Comment by araquejc** [comment]
BTW, you are welcome to close the issue.
