### ISSUE TITLE
Data set process

### ISSUE THREAD

**Issue by zjuKeLiu** [materialsvirtuallab/megnet#237]
Dear Megnet developers:
    I want to redo your work of training the network. So, may I have the codes of processing the dataset, "mp.2018.6.1.json" and " QM9" you provide in the paper.
    Thanks.

**Comment by chc273** [comment]
MP data are just processed using `CrystalGraph(cutoff=4.0)` and calling the `convert` method of it on pymatgen Structure. 

QM9 data are from a previous work by Faber et al. You can download their data at `10.1021/acs.jctc.7b00577`

**Comment by zjuKeLiu** [comment]
Thanks a lot for your answer. And I have another question: how can we get the Bulk Modulus, Shear Modulus, and Metal/Nonmetal Classification which are also used in your paper? We can not find them in "mp.2018.6.1.json" provided by you. 
Thanks

**Comment by chc273** [comment]
@zjuKeLiu The data are in the file. Only a subset of structures have those info

**Comment by zjuKeLiu** [comment]
Thanks again. And finally, could you please share the dataset "MP-2019.4.1" reported in this repo with us? We will cite your paper in ours.
Thanks

**Comment by chc273** [comment]
@zjuKeLiu https://github.com/materialsvirtuallab/megnet/tree/master/mvl_models/mp-2019.4.1 Check the readme.
