### ISSUE TITLE
Preprocessed QM9 dataset

### ISSUE THREAD

**Issue by yuanqidu** [materialsvirtuallab/megnet#247]
Is it possible to request the preprocessed QM9 dataset (similar to the example provided)? When I read the official QM9 dataset by Pybel, the molecularGraph converter reports quite a lot of errors (by rdkit). I have been struggling with providing the right QM9 dataset to run the model.

Thanks!

**Comment by chc273** [comment]
@yuanqidu we downloaded the data from Faber et al. https://pubs.acs.org/doi/suppl/10.1021/acs.jctc.7b00577/suppl_file/ct7b00577_si_001.pdf 


The dataset, as described in the SI of that paper, is at https://drive.google.com/open?id=0Bzn36Iqm8hZscHFJcVh5aC1mZFU

**Comment by yuanqidu** [comment]
May I ask another quick question? It looks like they don't have QM9 xyz information in their provided material. However, the molecule.json example has xyz info. Could you give a little guidance on that?

**Comment by chc273** [comment]
@yuanqidu you can generate the 3D structures (with xyz) using pybel. check this out. https://github.com/materialsvirtuallab/megnet/blob/40f8161acda720ae2e57c00f768743a235f3a2e9/megnet/data/molecule.py#L475

**Comment by pzhanggit** [comment]
> @yuanqidu we downloaded the data from Faber et al. https://pubs.acs.org/doi/suppl/10.1021/acs.jctc.7b00577/suppl_file/ct7b00577_si_001.pdf
> 
> The dataset, as described in the SI of that paper, is at https://drive.google.com/open?id=0Bzn36Iqm8hZscHFJcVh5aC1mZFU

Hi @chc273, thank you so much for posting the link. It seems not active now. Does it still work for you? Or do you maybe know any other places to download the processed dataset with 130462 molecules? Thanks.
