### ISSUE TITLE
Reproduce the result in "Graph Networks as a Universal Machine Learning"

### ISSUE THREAD

**Issue by zjuKeLiu** [materialsvirtuallab/megnet#252]
We are trying to reproduce the "formation energy" prediction result in "Graph Networks as a Universal Machine Learning Framework for Molecules and Crystals". But we wonder the parameter setings.

Following the paper, in our experiment, we set converter as:
`nfeat_bond = 100
r_cutoff = 4
gaussian_centers = np.linspace(0, r_cutoff + 1, nfeat_bond)
gaussian_width = 0.5
graph_converter = CrystalGraph(cutoff=r_cutoff)`

and define the model as 
`model = MEGNetModel(graph_converter=graph_converter, loss="mae", lr=1e-3, metrics=["mean_absolute_error"], dropout=0.5, centers=gaussian_centers, width=gaussian_width, nvocal=95, embedding_dim=16)`

finally define the callbacks as 
`callbacks = [ReduceLRUponNan(patience=500), ManualStop()]`

We train the model with 60,000 crystals from the dataset "mp.2018.6.1.json" and the remaining were divided equally between validation and test.

And the training stops at the 522ed epoch and the best validation mae is 0.099684 at the 21st epoch and the test mae is 0.1886

But we wonder the parameter setings in your experiment and any tricks can be shared ?
Thanks a lot.

**Comment by chc273** [comment]
@zjuKeLiu dropout is not needed, also dropping 50% is excessive.
