### ISSUE TITLE
Documentation, functionality help

### ISSUE THREAD

**Issue by hududed** [materialsvirtuallab/megnet#258]
Hi not sure where to ask this, I am interested in using this code to predict binding energy of a system. Is this possible? If this function needs to be developed, which source files would need editing?

Also, is there a more comprehensive documentation for megnet (just like pymatgen)?

**Comment by chc273** [comment]
@hududed I suppose the binding energy is a function of several structures (final structure - \sum isolated structures)? If that is the case, then you need to redo some network construction at the beginning. The MEGNet works by predicting the deterministic relationship from one structure to the target property.
