### ISSUE TITLE
REST query returned with error status code 403.

### ISSUE THREAD

**Issue by Yuxing0926** [materialsvirtuallab/megnet#293]
![image](https://user-images.githubusercontent.com/33997478/137098166-f475bd4a-6601-4fd3-a68f-156a647c4529.png)

**Comment by Wozi-dogz** [comment]
MPRestError: REST query returned with error status code 403. Content: b'{"valid_response": false, "error": "API_KEY is not a valid key.", "version": {"db": "2020_09_08", "pymatgen": "2022.0.8", "rest": "2.0"}, "created_at": "2022-08-25T06:24:51.581581"}
