### ISSUE TITLE
What is the difference performance using the .xyz files directly rather than the .json from Faber et al?

### ISSUE THREAD

**Issue by ivicts** [materialsvirtuallab/megnet#3]
I saw the megnet/data/molecule.py, it says that the implementation is in alpha version. Is there any difference in performance between using the .xyz files directly rather than the .json from Faber et al?

**Comment by chc273** [comment]
The json file contains all the atomic features as we listed in paper. As said, we.directly use those features.in paper. The xyz files do not have features. We are still testing to.reproduce the exact matches of features. The current version of molecule.py produce features that may not be the same as.in paper.
