### ISSUE TITLE
import pybel error

### ISSUE THREAD

**Issue by GalaxyRover59** [materialsvirtuallab/megnet#306]
Hello! I found in example
```
from megnet.utils.molecule import get_pmg_mol_from_smiles
from megnet.models import MEGNetModel

# same model API for molecule and crystals, you can also use the load_model method 
# as in previous example
model = MEGNetModel.from_file('mvl_models/qm9-2018.6.1/HOMO.hdf5')
# Need to convert SMILES into pymatgen Molecule
mol = get_pmg_mol_from_smiles("C")
model.predict_structure(mol)
```
it raised:
```
Traceback (most recent call last):
  File "D:/PycharmProjects/megnet/main.py", line 8, in <module>
    mol = get_pmg_mol_from_smiles('C')
  File "D:\Anaconda3\envs\tensorflow\lib\site-packages\monty\dev.py", line 96, in decorated
    raise RuntimeError(self.message)
RuntimeError: openbabel is needed to run convert smiles
```

I think the problem is in "megnet\utils\molecule.py", line 10:
`import pybel as pb`
which could be written as:
`from openbabel import pybel as pb`

And the next line can also be changed to
`from openbabel import openbabel as ob`
to avoid openbabel\\\__init__.py:14 warning:
"import openbabel" is deprecated, instead use "from openbabel import openbabel"

I don't know whether the problem is due to the IDE (I use PyCharm) or the version of the library, but the methods mentioned above seem to be useful.

**Comment by chc273** [comment]
@Huang-Yifan  PR #307 should have fixed this issue. Thanks
