### ISSUE TITLE
installation issue (RDKit and openbabel must be installed)

### ISSUE THREAD

**Issue by heliogabale** [materialsvirtuallab/megnet#332]
Hello
I tried both on my local computer and on google colab

I installed using both ways
1) pip install megnet
or 2) git clone ....

When I try to run

from megnet.data.molecule import MolecularGraph
from megnet.models import MEGNetModel

model = MEGNetModel(27, 2, 27, nblocks=1, lr=1e-2,
                    n1=4, n2=4, n3=4, npass=1, ntarget=1,
                    graph_converter=MolecularGraph())

I run into the following
RuntimeError: RDKit and openbabel must be installed

Installing openbabel separately result in dependencies conflict
Any ideas?
Thanks

**Comment by heliogabale** [comment]
Thanks for your reply, I finally found a workaround
I used conda and below is a copy of the YAML config file that is working for me  

name: megnet
channels:
  - openbabel
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - absl-py=1.0.0=pyhd8ed1ab_0
  - anyio=3.5.0=py37h89c1867_0
  - argon2-cffi=21.3.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py37h5e8e339_1
  - astor=0.8.1=pyh9f0ad1d_0
  - attrs=21.4.0=pyhd8ed1ab_0
  - babel=2.9.1=pyh44b312d_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - bleach=4.1.0=pyhd8ed1ab_0
  - boost=1.74.0=py37h796e4cb_4
  - boost-cpp=1.74.0=h359cf19_5
  - bottleneck=1.3.2=py37hb1e94ed_5
  - brotli=1.0.9=h7f98852_6
  - brotli-bin=1.0.9=h7f98852_6
  - brotlipy=0.7.0=py37h5e8e339_1003
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.18.1=h7f98852_0
  - ca-certificates=2020.10.14=0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.16.0=ha00ac49_1009
  - certifi=2020.6.20=py37_0
  - cffi=1.15.0=py37h036bc23_0
  - charset-normalizer=2.0.10=pyhd8ed1ab_0
  - colorama=0.4.4=pyh9f0ad1d_0
  - cryptography=36.0.0=py37h9ce1e76_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - dataclasses=0.8=pyhc8e2a94_3
  - debugpy=1.5.1=py37hcd2ae1e_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - entrypoints=0.3=pyhd8ed1ab_1003
  - flit-core=3.6.0=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.13.94=ha180cfb_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.29.0=py37h5e8e339_0
  - freetype=2.10.4=h0708190_1
  - gettext=0.19.8.1=h73d1719_1008
  - google-pasta=0.2.0=pyh8c360ce_0
  - greenlet=1.1.2=py37hcd2ae1e_1
  - grpcio=1.43.0=py37hd5d88b1_0
  - h5py=3.6.0=nompi_py37hd308b1e_100
  - hdf5=1.12.1=nompi_h7f166f4_103
  - icu=69.1=h9c3ff4c_0
  - idna=3.3=pyhd8ed1ab_0
  - importlib-metadata=4.10.1=py37h89c1867_0
  - importlib_resources=5.4.0=pyhd8ed1ab_0
  - ipykernel=5.3.4=py37h5ca1d4c_0
  - ipython=7.31.1=py37h89c1867_0
  - ipython_genutils=0.2.0=py_1
  - jarvis-tools=2022.1.10=pyhd8ed1ab_0
  - jbig=2.1=h7f98852_2003
  - jedi=0.18.1=py37h89c1867_0
  - jinja2=3.0.3=pyhd8ed1ab_0
  - joblib=1.1.0=pyhd8ed1ab_0
  - jpeg=9d=h36c2ea0_0
  - json5=0.9.5=pyh9f0ad1d_0
  - jsonschema=4.4.0=pyhd8ed1ab_0
  - jupyter_client=7.1.2=pyhd8ed1ab_0
  - jupyter_core=4.9.1=py37h89c1867_1
  - jupyter_server=1.13.4=pyhd8ed1ab_0
  - jupyterlab=3.2.8=pyhd8ed1ab_0
  - jupyterlab_pygments=0.1.2=pyh9f0ad1d_0
  - jupyterlab_server=2.10.3=pyhd8ed1ab_0
  - keras-applications=1.0.8=py_1
  - keras-preprocessing=1.1.2=pyhd8ed1ab_0
  - kiwisolver=1.3.2=py37h2527ec5_1
  - krb5=1.19.2=h48eae69_3
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - lerc=3.0=h9c3ff4c_0
  - libblas=3.9.0=13_linux64_openblas
  - libbrotlicommon=1.0.9=h7f98852_6
  - libbrotlidec=1.0.9=h7f98852_6
  - libbrotlienc=1.0.9=h7f98852_6
  - libcblas=3.9.0=13_linux64_openblas
  - libcurl=7.81.0=h494985f_0
  - libdeflate=1.8=h7f98852_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=11.2.0=h1d223b6_12
  - libgfortran-ng=11.2.0=h69a702a_12
  - libgfortran5=11.2.0=h5c6108e_12
  - libglib=2.70.2=h174f98d_1
  - libgomp=11.2.0=h1d223b6_12
  - libiconv=1.16=h516909a_0
  - liblapack=3.9.0=13_linux64_openblas
  - libnghttp2=1.43.0=ha19adfc_1
  - libnsl=2.0.0=h7f98852_0
  - libopenblas=0.3.18=pthreads_h8fe5266_0
  - libpng=1.6.37=h21135ba_2
  - libprotobuf=3.19.3=h780b84a_0
  - libsodium=1.0.18=h36c2ea0_1
  - libssh2=1.10.0=ha35d2d1_2
  - libstdcxx-ng=11.2.0=he4da1e4_12
  - libtiff=4.3.0=h6f004c6_2
  - libuuid=2.32.1=h7f98852_1000
  - libwebp-base=1.2.2=h7f98852_1
  - libxcb=1.13=h7f98852_1004
  - libxml2=2.9.12=h885dcf4_1
  - libzlib=1.2.11=h36c2ea0_1013
  - lz4-c=1.9.3=h9c3ff4c_1
  - markdown=3.3.6=pyhd8ed1ab_0
  - markupsafe=2.0.1=py37h5e8e339_1
  - matplotlib-base=3.5.1=py37h1058ff1_0
  - matplotlib-inline=0.1.3=pyhd8ed1ab_0
  - mistune=0.8.4=py37h5e8e339_1005
  - munkres=1.1.4=pyh9f0ad1d_0
  - nbclassic=0.3.5=pyhd8ed1ab_0
  - nbclient=0.5.10=pyhd8ed1ab_1
  - nbconvert=6.4.0=py37h89c1867_0
  - nbformat=5.1.3=pyhd8ed1ab_0
  - ncurses=6.3=h9c3ff4c_0
  - nest-asyncio=1.5.4=pyhd8ed1ab_0
  - nomkl=1.0=h5ca1d4c_0
  - notebook=6.4.7=pyha770c72_0
  - numexpr=2.8.0=py37hfe5f03c_100
  - numpy=1.21.5=py37hf2998dd_0
  - olefile=0.46=pyh9f0ad1d_1
  - openbabel=2.4.1=py37_6
  - openjpeg=2.4.0=hb52868f_1
  - openssl=3.0.0=h7f98852_2
  - packaging=21.3=pyhd8ed1ab_0
  - pandoc=2.17.0.1=h7f98852_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pcre=8.45=h9c3ff4c_0
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pip=21.3.1=pyhd8ed1ab_0
  - pixman=0.40.0=h36c2ea0_0
  - prometheus_client=0.12.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.24=pyha770c72_0
  - protobuf=3.19.3=py37hcd2ae1e_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pycairo=1.20.1=py37hfff247e_1
  - pycparser=2.21=pyhd8ed1ab_0
  - pygments=2.11.2=pyhd8ed1ab_0
  - pyopenssl=21.0.0=pyhd8ed1ab_0
  - pyparsing=3.0.7=pyhd8ed1ab_0
  - pyrsistent=0.18.1=py37h5e8e339_0
  - pysocks=1.7.1=py37h89c1867_4
  - python=3.7.12=hf930737_100_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.7=2_cp37m
  - pytz=2021.3=pyhd8ed1ab_0
  - pyzmq=22.3.0=py37h336d617_1
  - rdkit=2021.09.4=py37h13c2175_0
  - readline=8.1=h46c0cb4_0
  - reportlab=3.5.68=py37h69800bb_1
  - requests=2.27.1=pyhd8ed1ab_0
  - scipy=1.7.3=py37hf2a6cf1_0
  - send2trash=1.8.0=pyhd8ed1ab_0
  - setuptools=60.5.0=py37h89c1867_0
  - six=1.16.0=pyh6c4a22f_0
  - sniffio=1.2.0=py37h89c1867_2
  - spglib=1.16.3=py37hb1e94ed_0
  - sqlalchemy=1.4.31=py37h5e8e339_0
  - sqlite=3.37.0=h9cd32fc_0
  - termcolor=1.1.0=py_2
  - terminado=0.12.1=py37h89c1867_1
  - testpath=0.5.0=pyhd8ed1ab_0
  - tk=8.6.11=h27826a3_1
  - toolz=0.11.2=pyhd8ed1ab_0
  - tornado=6.1=py37h5e8e339_2
  - tqdm=4.62.3=pyhd8ed1ab_0
  - traitlets=5.1.1=pyhd8ed1ab_0
  - typing_extensions=4.0.1=pyha770c72_0
  - unicodedata2=14.0.0=py37h5e8e339_0
  - urllib3=1.26.8=pyhd8ed1ab_1
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - websocket-client=1.2.3=pyhd8ed1ab_0
  - werkzeug=2.0.2=pyhd8ed1ab_0
  - wheel=0.37.1=pyhd8ed1ab_0
  - wrapt=1.13.3=py37h5e8e339_1
  - xmltodict=0.12.0=py_0
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.0.10=h7f98852_0
  - xorg-libsm=1.2.3=hd9c2040_1000
  - xorg-libx11=1.7.2=h7f98852_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h7f98852_1
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h7f98852_1002
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.5=h516909a_1
  - zeromq=4.3.4=h9c3ff4c_1
  - zipp=3.7.0=pyhd8ed1ab_0
  - zlib=1.2.11=h36c2ea0_1013
  - zstd=1.5.2=ha95c52a_0
  - pip:
    - astunparse==1.6.3
    - cachetools==5.0.0
    - flatbuffers==2.0
    - future==0.18.2
    - gast==0.4.0
    - google-auth==2.5.0
    - google-auth-oauthlib==0.4.6
    - keras==2.7.0
    - libclang==12.0.0
    - megnet==1.2.9
    - monty==2022.1.19
    - mpmath==1.2.1
    - networkx==2.6.3
    - oauthlib==3.1.1
    - opt-einsum==3.3.0
    - palettable==3.3.0
    - pandas==1.3.5
    - pillow==9.0.0
    - plotly==5.5.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pymatgen==2022.0.17
    - requests-oauthlib==1.3.0
    - rsa==4.8
    - ruamel-yaml==0.17.20
    - ruamel-yaml-clib==0.2.6
    - scikit-learn==1.0.2
    - sympy==1.9
    - tabulate==0.8.9
    - tenacity==8.0.1
    - tensorboard==2.8.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorflow==2.7.0
    - tensorflow-estimator==2.7.0
    - tensorflow-io-gcs-filesystem==0.23.1
    - threadpoolctl==3.0.0
    - uncertainties==3.1.6
prefix: /home/simon/anaconda3/envs/megnet

**Comment by chc273** [comment]
@heliogabale thanks for sharing!
