### ISSUE TITLE
On the use of training data for megnet

### ISSUE THREAD

**Issue by okunoyukihiro2** [materialsvirtuallab/megnet#34]
Dear Megnet Developer.

I'm using megnet and appreciate your development of megnet.

Now, I used the pre-trained model of logK (/mp-2018.6.1/log10K.hdf5)

but Since I update (pip megnet) the megnet (and pymatgen),  the error has occured.
(old version of megnet and pymatgen, it worked.)

It's maybe some of my environment are old and it causes the error, but  if I get 
some advice, I'll be very happy.

Sincerely.

Here  this is my code 
##################################
from megnet.models import MEGNetModel
from megnet.data.graph import GaussianDistance
from megnet.data.crystal import CrystalGraph
from sklearn.model_selection import train_test_split

model_pretrained = MEGNetModel.from_file("../megnet/mvl_models/mp-2018.6.1/log10K.hdf5")
model_pretrained.model.summary()
########################################

and the error 

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-4cd31baec6ae> in <module>
      5 
      6 
----> 7 model_pretrained = MEGNetModel.from_file("../megnet/mvl_models/mp-2018.6.1/log10K.hdf5")
      8 model_pretrained.model.summary()

~/.conda/envs/mukimi_okuno/lib/python3.7/site-packages/megnet/models.py in from_file(cls, filename)
    299             GraphModel
    300         """
--> 301         configs = loadfn(filename + '.json')
    302         from keras.models import load_model
    303         from megnet.layers import _CUSTOM_OBJECTS

~/.conda/envs/mukimi_okuno/lib/python3.7/site-packages/monty/serialization.py in loadfn(fn, *args, **kwargs)
     81                 if "cls" not in kwargs:
     82                     kwargs["cls"] = MontyDecoder
---> 83                 return json.load(fp, *args, **kwargs)
     84 
     85 

~/.conda/envs/mukimi_okuno/lib/python3.7/json/__init__.py in load(fp, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    294         cls=cls, object_hook=object_hook,
    295         parse_float=parse_float, parse_int=parse_int,
--> 296         parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
    297 
    298 

~/.conda/envs/mukimi_okuno/lib/python3.7/json/__init__.py in loads(s, encoding, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    359     if parse_constant is not None:
    360         kw['parse_constant'] = parse_constant
--> 361     return cls(**kw).decode(s)

~/.conda/envs/mukimi_okuno/lib/python3.7/site-packages/monty/json.py in decode(self, s)
    254     def decode(self, s):
    255         d = json.JSONDecoder.decode(self, s)
--> 256         return self.process_decoded(d)
    257 
    258 

~/.conda/envs/mukimi_okuno/lib/python3.7/site-packages/monty/json.py in process_decoded(self, d)
    246 
    247             return {self.process_decoded(k): self.process_decoded(v)
--> 248                     for k, v in d.items()}
    249         elif isinstance(d, list):
    250             return [self.process_decoded(x) for x in d]

~/.conda/envs/mukimi_okuno/lib/python3.7/site-packages/monty/json.py in <dictcomp>(.0)
    246 
    247             return {self.process_decoded(k): self.process_decoded(v)
--> 248                     for k, v in d.items()}
    249         elif isinstance(d, list):
    250             return [self.process_decoded(x) for x in d]

~/.conda/envs/mukimi_okuno/lib/python3.7/site-packages/monty/json.py in process_decoded(self, d)
    236                            if not k.startswith("@")}
    237                     if hasattr(cls_, "from_dict"):
--> 238                         return cls_.from_dict(data)
    239             elif np is not None and modname == "numpy" and classname == \
    240                     "array":

~/.conda/envs/mukimi_okuno/lib/python3.7/site-packages/megnet/data/graph.py in from_dict(cls, d)
    170             d.update({'nn_strategy': nn_strategy_obj})
    171             return super().from_dict(d)
--> 172         return super().from_dict(d)
    173 
    174 

~/.conda/envs/mukimi_okuno/lib/python3.7/site-packages/monty/json.py in from_dict(cls, d)
    124         decoded = {k: MontyDecoder().process_decoded(v) for k, v in d.items()
    125                    if not k.startswith("@")}
--> 126         return cls(**decoded)
    127 
    128     def to_json(self):

TypeError: __init__() got an unexpected keyword argument 'atom_convertor'

**Comment by chc273** [comment]
Please update megnet, install it from github and download the model files on github. In new versions, `atom_convertor` has been renamed `atom_converter`. That's what causing this issue.

**Comment by okunoyukihiro2** [comment]
Thank you for your advice.
 
I had installed development version of megnet, and model files.
I confirmed the script worked.

Sincerely, 

Yukihiro Okuno
