### ISSUE TITLE
Return history of the model using .train_from_graphs

### ISSUE THREAD

**Issue by dembart** [materialsvirtuallab/megnet#359]
Hi, 
Is it possible to return history of the model during training from the graphs? (train, validations errors)

**Comment by chc273** [comment]
You can. This step https://github.com/materialsvirtuallab/megnet/blob/02e15ee1a69cbdc318965be12c6dd94b8c1cb144/megnet/models/base.py#L230 returns the history. You can do some modification and return the history.
