### ISSUE TITLE
Python Files Missing in PyPi Distribution

### ISSUE THREAD

**Issue by WardLT** [materialsvirtuallab/megnet#4]
I am having trouble installing megnet from pypi, and it seems like there's an issue with the `whl` file provided via pypi. It does not seem to contain any Python files:

![image](https://user-images.githubusercontent.com/7003149/57256371-18dc5980-701c-11e9-8e83-2840c1ef4427.png)

I am not sure how you are doing your publishing to PyPi, but there seems to be an issue in your deployment code.

**Comment by shyuep** [comment]
Thanks for reporting this. I have fixed the problem and released a working version. There was a missing "packages" keyword in the setup.py which was mistakenly written as "package" and somehow python just proceeded to allow release.
