### ISSUE TITLE
On the use of training molecule data for megnet

### ISSUE THREAD

**Issue by rookiecoder-chen** [materialsvirtuallab/megnet#44]
Dear Megnet Developer.

I'm using megnet and appreciate your development of megnet. I want to train the model on my own molecular data set. How can I process my data set and what format should I format the molecular data?

Sincerely.

**Comment by chc273** [comment]
Please check the `notebooks` folder and in particular, https://github.com/materialsvirtuallab/megnet/blob/master/notebooks/molecule_example.ipynb
and see if that helps.

**Comment by rookiecoder-chen** [comment]
Are all the data typed in JSON files generated by pymatgen?

**Comment by chc273** [comment]
You can generate the xyz information from molecule using pymatgen, which is used in the example. Pymatgen also has interface to other format (check pymatgen.io module) so many other molecule formats can be converted to pymatgen format. 

Those require the installation of openbabel (pybel). 
The other option is that you can wrap Pymatgen Molecule with megnet.utils.molecule.MEGNetMolecule, and then you can use the crystal_example.ipynb to train the model by putting the new molecules in the place of crystal structures. This option does not require other software installation.

**Comment by rookiecoder-chen** [comment]
Excuse me, sir. What's the difference between molecular model and QM9 model? I don't quite understand how a molecule data (such as cif. XYZ file) can be transformed into input for a graph model. Does the input for training the model have to be processed in JSON format? Can you tell me what the model typing looks like? Thank you very much for your reply.

**Comment by chc273** [comment]
QM9 models are molecular models. ok, then https://github.com/materialsvirtuallab/megnet/blob/master/notebooks/molecule_example.ipynb. This example has the necessary steps. Why dont you try to run the example and then substitute your data in. The inputs do not need to be processed in JSON. JSON is just convenient for sharing the data. 

What do you mean model typing? If you want to know the details, please check the codes.
