### ISSUE TITLE
Question about notebooks

### ISSUE THREAD

**Issue by rookiecoder-chen** [materialsvirtuallab/megnet#56]
Hello, I have some questions:

1. I tried to train my own data with the latest 'qm9_simple_model' uploaded in notebnooks. It works! but I want to know that the program trains molecular data. Why call crystal related modules? How are they related?
gc = CrystalGraph(bond_converter=GaussianDistance(np.linspace(0, 5, 100), 0.5), cutoff=4)
model = MEGNetModel(100, 2, graph_converter=gc)
What are the parameters of 100 and 2?
2. Is there any difference or connection between qm9_simple_model, molecule_example and qm9_example?

I am looking forward to your reply, thanks！

**Comment by chc273** [comment]
1. The crystal graph does two things, i) convert the atoms to their atomic numbers as atom features, ii) use the distances between atoms as bond features. Any structure that you want to express its graph in this way can use the crystal graph.
For the parameters, you should check the documentation of the methods. 100 is the number of bond features and 2 is the number of global attribute features. 
2. They differ in how the graph is constructed. There are differences in how to convert atom to atomic features as well as how to define bonds and bond attributes.
