### ISSUE TITLE
How to make reference log10K.hdf5 file 

### ISSUE THREAD

**Issue by okunoyukihiro2** [materialsvirtuallab/megnet#6]
Dear  Megnet developers 

I enjoyed the megnet  and appreciate releasing the source code of megnet. 
I had tried to train the log of elastic moduli (log10K) by megnet with 
almost default parameter values and the date is divided data (mp_elas.json) 
into 80:10:10 (train, validation, test) and verified the model  performance in the test data. 
The result for test data is MAE (log10 K)  is 0.097 and is less accurate than the 
reference paper (Graph Networks as a Universal Machine Learning Framework for Molecules and Crystal).

My python script is as follow,

nfeat_bond = 10
nfeat_global = 2 # number of state freedom
gaussian_centers = np.linspace(0, 5, 10)
gaussian_width = 0.5
distance_convertor = GaussianDistance(gaussian_centers, gaussian_width)
graph_convertor = CrystalGraph(bond_convertor=distance_convertor)

targets =data[target_cols[0]]
X = structures #5    (mp_elas.  structure data) 
Y = targets   #  ( mp elas  target elastic value)

! split data into 80;10:10 (train , valid , test) 
X_train , X_test, Y_train, Y_test = train_test_split(X,Y,test_size=0.1,random_state=1)
X_train, X_val, Y_train, Y_val = train_test_split(X_train,Y_train,test_size=(10.0/90.0),random_state=1)

callback_list =[ManualStop(),ReduceLROnPlateau(monitor='val_loss',factor=0.1,patience=10),
               ModelCheckpoint(filepath='./megnet_mp_elas2.h5',monitor='val_loss',save_best_only=True)               
               ]
megmodel =MEGNetModel(nfeat_bond, nfeat_global,graph_convertor=graph_convertor)
megmodel.model.summary()

! batch_size 24 (default) epochs=30  we stop number of epoch 30  
megmodel.train(X_train,Y_train,X_val,Y_val,batch_size=24,epochs=30,callbacks=callback_list)

And I found the  released leaned model (log10K.hdf5)  has first bond attributes dimension 
is 6464 (input_2[0][0] of dense_3 layer before MEGNetLayer 1 .) , and is different from 
my default values  as follow 

! my layer structure (defalut use of MegNetModel) 
dense_3 (Dense)                 (None, None, 64)     704         input_2[0][0] 

!log10K.hdf5
dense_3 (Dense)                 (None, None, 64)     6464        input_2[0][0]

What cause the difference of the dimension of dense_3 layer if MegNetModel? 
        
I'm beginner in deep learning and  might have made a simple  mistake.
If I can get reply or get the python script that made   released log10K.hdf5 , I'm very happy. 

Sincerely,

Yukihiro Okuno.

**Comment by chc273** [comment]
Hi I hope you already solved the problem. The parameters you mentioned are in fact not our defaults. The example was meant to give a minimal model everyone can run on laptop. The batch size and epoch number defaults are 128 and 1000, as implemented in our code. nfeat_bond is 100 not 10. Please also change the Gaussian expansion length to 100 to match the bond length. Lastly no need to change the callbacks, what you are showing are already in defaults. I hope this answers your questions.
