### ISSUE TITLE
Batch training error and NaN loss from the first epoch

### ISSUE THREAD

**Issue by yanselmo** [materialsvirtuallab/megnet#66]
Hi, I'm beginenr with deep learning.

I'm tring to use MEGNetmodel (and my own model using MEGNet layers) for materials property prediction now. 

when I tried to train the model, I get some problems. 
First, I get an error message with using MolecularBatchGenerator.

the message is,
ValueError: Error when checking target: expected dense_8 to have shape (None, 1) but got array with shape (1, 4) 

I thought this error is due to MolecularBatchGenerator so I made my own graphbatchgenerator, (generator with transposed target).

```
def __getitem__(self, index: int) -> tuple:
        # Get the indices for this batch
        batch_index = self.mol_index[index * self.batch_size:(index + 1) * self.batch_size]

        # Get the inputs for each batch
        inputs = self._generate_inputs(batch_index)

        # Make the graph data
        inputs = self._combine_graph_data(*inputs)

        # Return the batch
        if self.targets is None:
            return inputs
        else:
            # get targets
            it = itemgetter(*batch_index)
            target_temp = itemgetter_list(self.targets, batch_index)
            target_temp = np.atleast_2d(target_temp).transpose()

            return inputs, expand_1st(target_temp)
```

(other things are all same except target_temp = np.atleast_2d(target_temp).transpose()

After changing MolecularBatchGernerator with this, I could start to train.

However, when I start to train the model, I get an nan loss from the first epoch which is totally frustrating me... actually, I get nan value for all metrics. At the start of the training, their values are real value. But after trained with several batch, the model gives nan metrics.

I heard several method to solve nan problems in deep learning, so I tried most of them: I have done output scaling, changing the loss function, using other optimizer, reduce(or increase) batch size, gradient clipping, and changing the model structure.

Do you have any other insights for solve the nan loss problem??
I've spent several days for this problem.. TT

**Comment by chc273** [comment]
Hmm, I can not really tell where the problem is without knowing the specific data you are using and your model architecture. 

Did you try the example notebooks in the repo? We provide molecule examples which you should find similarities to your tasks.

For the nan loss, yes we observe that too. Our strategy is to reduce the learning rate and reset optimizer states before continuing training. It works for us and is included in default megnet training routine ( see ReduceLRUponNan in callbacks)


I hope you can solve your problem soon.
