### ISSUE TITLE
is the pretrained model qm9-2018.6.1 trained with all qm9 data or a part of qm9 data?

### ISSUE THREAD

**Issue by liuxiaotong15** [materialsvirtuallab/megnet#96]
Excuse me. I wonder if the model is trained use the whole 134K data in qm9 or not? Many thanks.

**Comment by chc273** [comment]
@liuxiaotong15 
131k data points to be exact. There are ~3000 data failed consistency check.

**Comment by chc273** [comment]
@liuxiaotong15 
The 131K molecules are split into 90:5:5 ratios for train:validation:test.

**Comment by liuxiaotong15** [comment]
thanks
