### ISSUE TITLE
the unit of Gibbs free enegy is kj/mol or eV

### ISSUE THREAD

**Issue by liuxiaotong15** [materialsvirtuallab/megnet#97]
hi
I saw the error is 0.012eV of Gibbs free energy
but in qm9 pretrained notebook, it lists below:
mu	-0.008	0.000
alpha	13.127	13.210
HOMO	-10.557	-10.550
LUMO	3.241	3.186
gap	13.622	13.736
R2	35.975	35.364
ZPVE	1.215	1.218
U0	-17.166	-17.172
U	-17.353	-17.286
H	-17.420	-17.389
G	-16.107	-16.152
Cv	6.427	6.469
omega1	3151.626	3151.708

so the unit here of Gibbs is eV or kj/mol?

thanks

**Comment by liuxiaotong15** [comment]
by the way, Do you calculate the qm9 standard Gibbs yourself or get from other place?
thanks

**Comment by liuxiaotong15** [comment]
I guess the gibbs energy here is the molecule atomization energy, right?

**Comment by chc273** [comment]
@liuxiaotong15 qm9_pretrained.ipynb shows the prediction results for a specific molecule compared to the DFT results. Those are not errors for each model. Please read the context of the notebook. The units are eV. 

The QM9 data are from literature, please check the paper for its origin. 

Yes the gibbs energy is computed by subtracting atomic references.

**Comment by liuxiaotong15** [comment]
thank you very much. and my result have a fixed 3-5 ev difference with you, so I guess maybe my atomic references is different with you? I use 
'H': -13.90, 'C': -1030.26, 'N': -1485.71, 'O': -2043.02, 'F': -2713.89
what about yours?

**Comment by chc273** [comment]
We used data processed by "Journal of chemical theory and computation 13.11 (2017): 5255-5264"

The data was shared by the authors at https://drive.google.com/open?id=0Bzn36Iqm8hZscHFJcVh5aC1mZFU

**Comment by liuxiaotong15** [comment]
thanks
